feat: support configuration file operation api
polarismesh/polaris-go pull request #175
Opened 2023-09-26 13:38 UTC by wenxuan70

**Please provide issue(s) of this PR:**
Fixes #164

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Performance and Scalability
- [ ] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2023-09-26 13:49 UTC, houseme commented on pkg/flow/configuration/config_flow.go
> +		version := resp.GetConfigFile().GetVersion()
198行 可以卸载210行前面

2023-09-26 13:51 UTC, houseme commented on pkg/flow/configuration/config_flow.go
> +		log.GetBaseLogger().Errorf("[Config] update config file with unexpected code.",
是不是可以记录为info 日志即可，也不需要打印堆栈信息

2023-09-26 13:53 UTC, houseme commented on pkg/flow/configuration/config_flow.go
> +			fileRepo := c.configFilePool[cacheKey]
上面243行 version可以写在使用处前面

2023-09-26 13:54 UTC, houseme commented on pkg/flow/configuration/config_flow.go
> +	} else {
else 是不可以省略，直接记录信息和返回错误 ？

2023-09-26 15:07 UTC, wenxuan70 commented on pkg/flow/configuration/config_flow.go
> +		version := resp.GetConfigFile().GetVersion()
好的

2023-09-26 15:39 UTC, chuntaojun requested changes

2023-09-26 15:39 UTC, chuntaojun commented on pkg/flow/configuration/config_flow.go
> +	cacheKey := genCacheKeyByMetadata(configFileMetadata)
这个 cacheKey 的检查是不是不需要？

2023-09-26 15:39 UTC, chuntaojun commented on pkg/flow/configuration/config_flow.go
> +func (c *ConfigFileFlow) CreateConfigFile(namespace, fileGroup, fileName, content string) error {
需要前置参数检查

2023-09-27 04:02 UTC, wenxuan70 commented on pkg/flow/configuration/config_flow.go
> +func (c *ConfigFileFlow) CreateConfigFile(namespace, fileGroup, fileName, content string) error {
在util.go文件下增加了`CheckConfigFileMetadata`方法来检查参数

2023-10-07 03:18 UTC, chuntaojun requested changes

2023-10-07 03:18 UTC, chuntaojun commented on api.go
> +	// CreateConfigFile create configuration file
入参数换成 struct 定义

2023-10-07 03:21 UTC, merged