[WIP][ISSUE #71]support async register
polarismesh/polaris-go pull request #72
Opened 2022-07-05 10:17 UTC by shichaoyuan

**Please provide issue(s) of this PR:**
Fixes #71 

**To help us figure out who should review this PR, please put an X in all the areas that this PR affects.**

- [ ] Configuration
- [ ] Docs
- [ ] Performance and Scalability
- [X] Naming
- [ ] HealthCheck
- [ ] Test and Release

**Please check any characteristics that apply to this pull request.**

- [ ] Does not have any user-facing changes. This may include API changes, behavior changes, performance improvements, etc.

2022-07-05 15:22 UTC, chuntaojun requested changes

2022-07-05 15:22 UTC, chuntaojun commented on api/provider_impl.go
>  type providerAPI struct {
providerAPI 应该不适合维护一些状态信息，应该统一到SDKContext中，providerAPI 主要还是代理SDKContext以及Engine中的接口，数据维护以及状态管理还是需要放在 SDKContext 中比较好

2022-07-06 14:36 UTC, shichaoyuan commented on api/provider_impl.go
> +	mutex            *sync.Mutex
sync.Mutex or *sync.Mutex
请教一下这个小细节有啥讲究？

2022-07-06 15:19 UTC, shichaoyuan commented on api/provider_impl.go
>  type providerAPI struct {
嗯，看了一下，放在 sdkContext 这里也不太合适，可能移到 Engine 中比较合适。

2022-07-07 00:52 UTC, chuntaojun commented on api/provider_impl.go
> +	mutex            *sync.Mutex
can see this guide: https://github.com/xxjwxc/uber_go_guide_cn

2022-07-07 02:08 UTC, shichaoyuan commented on api/provider_impl.go
> +	mutex            *sync.Mutex
> can see this guide: https://github.com/xxjwxc/uber_go_guide_cn

学习一下

2022-07-07 14:24 UTC, chuntaojun commented on pkg/flow/async_flow.go
> +func (e *Engine) runAsyncRegisterTask(state *registerState) {
runAsyncRegisterTask -> runHeartbeat

2022-07-07 14:24 UTC, chuntaojun commented on pkg/flow/async_flow.go
> +			if ec != 400141 {
400141 -> ErrorCode_HeartbeartOnDisable

2022-07-07 14:24 UTC, chuntaojun commented on pkg/flow/async_flow.go
> +			if now.Before(state.lastRegisterTime.Add(minInterval)) {
time.Since(state.lastRegisterTime) > minInrterval

2022-07-07 14:24 UTC, chuntaojun commented on pkg/model/service.go
> +func (g *InstanceRegisterRequest) SetRegisterVersion(v int) {
not export let user know this func

2022-07-07 14:24 UTC, chuntaojun commented on pkg/model/error.go
> +	return &sdkError{
&sdkError{
		errCode:    errCode,
		errDetail:  fmt.Spring(msg, args),
		cause:      cause,
		serverCode: serverCode,
		serverInfo: serverInfo,
	}

2022-07-08 02:17 UTC, shichaoyuan commented on pkg/flow/async_flow.go
> +				break
这里 break 的是 select，for循环只有在收到 stoppedchan 才会结束

2022-07-08 03:21 UTC, chuntaojun requested changes

2022-07-08 03:21 UTC, chuntaojun commented on pkg/model/engine.go
> +	AsyncRegister(Instance *InstanceRegisterRequest) (*InstanceRegisterResponse, error)
AsyncRegister 不合适，在SDK内，这不是一个异步逻辑，异步是在服务端处理的，需要重新设计一个FunName

2022-07-08 05:34 UTC, shichaoyuan commented on pkg/model/engine.go
> +	AsyncRegister(Instance *InstanceRegisterRequest) (*InstanceRegisterResponse, error)
嗯，没想到什么合适的，改成 SyncRegisterV2 吧，从行为上来说还是同步逻辑。

2022-07-08 06:39 UTC, chuntaojun commented on pkg/model/engine.go
> +	AsyncRegister(Instance *InstanceRegisterRequest) (*InstanceRegisterResponse, error)
是的，在SDK内不需要体现服务端的处理逻辑，方法命名只表现在SDK内的执行逻辑是怎么样的

2022-07-11 11:35 UTC, chuntaojun commented on pkg/flow/advan_flow.go
> +	log.GetBaseLogger().Infof("async register task started {%s, %s, %s:%d}",
[HeartBeat] instance heartbeat task started {%s, %s, %s:%d}

2022-07-11 11:35 UTC, chuntaojun commented on pkg/flow/advan_flow.go
> +			log.GetBaseLogger().Infof("async register task stopped {%s, %s, %s:%d}",
[HeartBeat] instance heartbeat task stopped {%s, %s, %s:%d}

2022-07-18 06:29 UTC, chuntaojun commented on pkg/model/service.go
> +	DefaultHeartbeatTtl int = 20
和服务端保持一致，默认为5 second 吧

2022-07-19 02:07 UTC, chuntaojun submitted a review, later dismissed

2022-07-27 07:53 UTC, chuntaojun approved these changes

2022-07-28 03:48 UTC, chuntaojun approved these changes

2022-07-28 03:50 UTC, shichaoyuan commented
https://github.com/polarismesh/polaris/issues/429

2022-07-28 04:39 UTC, liu-song approved these changes

2022-07-29 08:58 UTC, merged